[package]
name = "lightproc"
version = "0.2.1-alpha.0"
description = "Lightweight process abstraction for Rust"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
keywords = ["fault-tolerant", "runtime", "actor", "system"]
categories = []
edition = "2018"

[dependencies]
rustc-hash = "1.0.1"
