[package]
name = "bastion-executor"
version = "0.2.1-alpha.0"
description = "Fault-tolerant Runtime for Rust applications"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
keywords = ["fault-tolerant", "runtime", "actor", "system"]
categories = []
edition = "2018"


[dependencies]
crossbeam-utils = "0.6"
crossbeam-epoch = "0.7"
lazy_static = "1.4"
libc = "0.2"
num_cpus = "1.10"
rustc-hash = "1.0.1"
pin-utils = "0.1.0-alpha.4"
numanji = "^0.1"
allocator-suite = "^0.1"

[target.'cfg(not(any(target_os = "android", target_os = "linux")))'.dependencies]
jemallocator = "^0.3"

lightproc = "^0.3"
