[package]
name = "bastion"
version = "0.2.1-alpha.0"
description = "Fault-tolerant Runtime for Rust applications"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
keywords = ["fault-tolerant", "runtime", "actor", "system"]
categories = []
homepage = "https://github.com/bastion-rs/bastion"
repository = "https://github.com/bastion-rs/bastion"
documentation = "https://docs.rs/bastion"
readme = "README.md"
license = "Apache-2.0/MIT"
edition = "2018"
exclude = [
	".github/*",
	"examples/*",
	"graphstore/*",
	"tests/*",
	"img/*",
	"ci/*",
	"benches/*",
	"doc/*",
	"*.png",
	"*.dot",
	"*.yml",
	"*.toml",
	"*.md"
]

[badges]
travis-ci = { repository = "bastion-rs/bastion", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
#backtrace = "0.3.32"
chashmap = "2.2"
#crossbeam-channel = "0.3.8"
#ctrlc = "3.1.3"
#ego-tree = "0.6.0"
#env_logger = "0.6.1"
#futures = "0.1.28"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
fxhash = "0.2"
lazy_static = "1.4"
#log = "0.4.7"
objekt = "0.1"
qutex = { version = "0.2", features = ["async_await"] }
#ratelimit = "0.4.4"
runtime = "=0.3.0-alpha.7"
#tokio = "^0.1"
#tokio-executor = "0.1.8"
#tokio-threadpool = "0.1.15"
uuid = { version = "0.7", features = ["v4", "const_fn"] }
