name: Discord Notification

on: [pull_request, pull_request_review, pull_request_review_comment, commit_comment, issues, milestone]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
